'From Cuis6.3 [latest update: #6293] on 27 March 2024 at 8:42:25 pm'!
'Description Tests for OMeta2.  These are tests for the Extensions and Examples packages.

Note: the main OMeta2 package is effectively both a set of unit and system tests for OMeta itself, as it rewrites the bulk of OMeta in OMeta. If you are able to successfully load the OMeta2 package, you can be confident that its core functionality is working correctly.  The tests included in this package validate the remaining functionality that the core package does not exercise.'!
!provides: 'OMeta2Tests' 2 11!
!requires: 'OMeta2Examples' 2 0 nil!


